require 'pod_builder/core'

PodBuilder::Configuration::load

platform :ios, '9.0'

use_frameworks!

target 'PodBuilderExample' do
  # Pods for PodBuilderExample
  pod 'Alamofire' # Swift sample
  pod 'AFNetworking' # Objective-C sample
  pod 'Loop' # Assets

  # Firebase
  # pod 'Firebase'
  # pod 'FirebaseCore'
  # pod 'FirebaseDatabase'
  # pod 'FirebaseAuth'
  # pod 'FirebaseFirestore'
  # pod 'FirebasePerformance'
  # pod 'FirebaseCrashlytics'
end

pre_install do |installer|
  raise "\n🚨  Do not launch 'pod install' manually, use `pod_builder` instead!\n" if !File.exist?('pod_builder.lock')
end
